services:
  - type: web
    name: encryption-app
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node server/app.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: encryption-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production

databases:
  - name: encryption-db
    plan: free
    databaseName: encryption
    user: encryption_user